//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ieye.rc
//
#define VERINFO                         1
#define IEYEICO                         2
#define FOLDEROPENICO                   3
#define FOLDERCLOSEDICO                 4
#define CHECKBTNBMP                     9
#define REPORTDLG                       10
#define ASSFILESDLG                     11
#define RESAMPLEDLG                     12
#define FILEOPENDLG                     13
#define SETUPDLG                        14
#define PVPDLG                          15
#define PGPDLG                          16
#define POPDLG                          17
#define PIPDLG                          18
#define PAPDLG                          19
#define CLRDLG                          20
#define CSSDLG                          22
#define FILERENAMEDLG                   23
#define XYSCROLLCUR                     30
#define XSCROLLCUR                      31
#define YSCROLLCUR                      32
#define VIEWER_MENU                     35
#define INDEX_MENU                      36
#define FROZEN_MENU                     37
#define REPORT_TITLE                    97
#define REPORT_PERC                     98
#define FMJSOFT                         99
#define CMD_SPAWNNEW                    100
#define CMD_SPAWNNEXTIMAGE              101
#define CMD_SPAWNPREVIMAGE              102
#define CMD_PROPERTIES                  103
#define CMD_ONSHOWHIDEWAITCURSOR        104
#define CMD_ONRUNNINGSLIDESHOW          105
#define CMD_HELP                        106
#define CMD_BRINGTOFOREGROUND           107
#define CMD_ONNEWIMAGE                  108
#define CMD_LOADNEW                     109
#define CMD_SAVEAS                      110
#define CMD_DELETE                      111
#define CMD_RECYCLE                     112
#define CMD_SLIDECANCEL                 113
#define CMD_SIZE2WINDOW                 114
#define CMD_SIZE2IMAGE                  115
#define CMD_SIZERESTORE                 116
#define CMD_CLIPBCOPY                   117
#define CMD_CLIPBPASTE                  118
#define CMD_SLIDEAUTO                   119
#define CMD_EXIT                        120
#define CMD_SETWALLPAPER                121
#define CMD_RECREATE                    122
#define CMD_MANUALRECREATE              123
#define CMD_NEXTIMAGE                   124
#define CMD_PREVIMAGE                   125
#define CMD_SLIDESHOW                   126
#define CMD_INDEX                       127
#define CMD_SAVECACHE                   128
#define CMD_REMOVECACHE                 129
#define CMD_SORT_PATH                   130
#define CMD_SORT_NAME                   131
#define CMD_SORT_FILESIZE               132
#define CMD_SORT_FILEDATE               133
#define CMD_SORT_IMAGESIZE              134
#define CMD_EDITSLIDE                   135
#define CMD_ZOOM2XHEURISTIC             139
#define CMD_ZOOM10                      140
#define CMD_ZOOM25                      141
#define CMD_ZOOM50                      142
#define CMD_ZOOM75                      143
#define CMD_ZOOM100                     144
#define CMD_ZOOM150                     145
#define CMD_ZOOM200                     146
#define CMD_ZOOM300                     147
#define CMD_ZOOM400                     148
#define CMD_ZOOM_IN                     149
#define CMD_ZOOM_OUT                    150
#define CMD_ADJUSTIMAGE                 151
#define CMD_CAPTURESCREEN               153
#define CMD_CAPTUREWINDOW               154
#define CMD_NEGATIVE                    155
#define CMD_TRIM2WINDOW                 156
#define CMD_DELETE_SHOWNEXT             157
#define CMD_KILLEMALL                   158
#define CMD_FULLSCREENTOGGLE            159
#define CMD_RELOAD                      160
#define CMD_SENDTOBACK                  161
#define CMD_CLRPICK                     162
#define CMD_ROTATE_90                   163
#define CMD_ROTATE_180                  164
#define CMD_ROTATE_270                  165
#define CMD_MIRROR_VERT                 166
#define CMD_MIRROR_HORIZ                167
#define CMD_RENAME                      168
#define CMD_NEXTWINDOW                  169
#define CMD_PREVWINDOW                  170
#define CMD_TOPMOSTTOGGLE               171
#define CMD_FREEZE                      172
#define CMD_AUTOLOAD                    174
#define CMD_SHOW_DIRS                   177
#define CMD_SHOW_OTHER                  178
#define CMD_SHOW_NAME1                  179
#define CMD_SHOW_NAME2                  180
#define CMD_SHOW_NAME3                  181
#define CMD_SHOW_NAME4                  182
#define CMD_SHOW_RES                    183
#define CMD_SHOW_EXT                    184
#define CMD_SHOW_SIZE                   185
#define CMD_SHOW_DATE                   186
#define CMD_SHOW_COMMENT                187
#define CMD_COPY                        188
#define CMD_MOVE                        189
#define CMD_ERASE                       190
#define CMD_ERASE_SHOWNEXT              191
#define CMD_SLIDEFULLSCREEN             192
#define CMD_FILEINFO                    193
#define CMD_FIRSTIMAGE                  194
#define CMD_LASTIMAGE                   195
#define CMD_RECURSESUBDIRS              196
#define CMD_GOFULLSCREEN                197
#define CMD_GOWINDOWED                  198
#define PAP_WWW                         201
#define PAP_DONATE                      202
#define PAP_LOGO                        203
#define PAP_INFO                        204
#define PAP_IEYE                        205
#define PAP_IDEBUG                      206
#define PVP_HIDECAPTION                 220
#define PVP_RUNMAXIMIZED                221
#define PVP_TITLERES                    222
#define PVP_AUTOSIZEIMAGE               223
#define PVP_AUTOSHRINKLARGE             224
#define PVP_FULLPATH                    225
#define PVP_OVERLAY1TYPE                227
#define PVP_OVERLAY1POS                 228
#define PVP_OVERLAY2TYPE                229
#define PVP_OVERLAY2POS                 230
#define PVP_OVERLAY3TYPE                231
#define PVP_OVERLAY3POS                 232
#define PVP_ONLYAUTOSHRINK              233
#define PVP_GLASSEFFECT                 234
#define PVP_BGCOLOR                     235
#define PVP_AUTOBGCOLOR                 236
#define PVP_GLASSEFFECT2                236
#define PIP_ICONX                       240
#define PIP_ICONY                       241
#define PIP_ICONSPACING                 242
#define PIP_COMPRESSCACHE               243
#define PIP_AUTOCREATECACHE             244
#define PIP_CACHEDSIZEOVERRIDES         245
#define PIP_CLOSEONOPEN                 246
#define PIP_FULLPATH                    247
#define PIP_NUMFILES                    248
#define PIP_GLASSEFFECT                 249
#define PIP_BGCOLOR                     250
#define POP_CLEARRECENTONEXIT           255
#define POP_CLEARRECENTNOW              256
#define POP_LANGUAGE                    257
#define POP_EDITFILETYPES               258
#define PFP_TYPES                       260
#define OF_RECENT                       270
#define OF_INDEX                        271
#define OF_HELP                         272
#define OF_INFO                         273
#define OF_PREVIEW                      274
#define CLR_CONTRAST                    280
#define CLR_CONTRAST_VAL                281
#define CLR_BRIGHTNESS                  282
#define CLR_BRIGHTNESS_VAL              283
#define CLR_SHARPNESS                   284
#define CLR_SHARPNESS_VAL               285
#define CLR_HUE                         286
#define CLR_HUE_VAL                     287
#define CLR_SAT                         288
#define CLR_SAT_VAL                     289
#define CLR_LUM                         290
#define CLR_LUM_VAL                     291
#define CLR_R                           292
#define CLR_R_VAL                       293
#define CLR_G                           294
#define CLR_G_VAL                       295
#define CLR_B                           296
#define CLR_B_VAL                       297
#define CLR_GAMMA                       298
#define CLR_GAMMA_VAL                   299
#define CLR_INV                         300
#define CLR_RESET                       301
#define CLR_SAVE                        302
#define CLR_ROTATE                      303
#define CLR_MIRRORV                     304
#define CLR_MIRRORH                     305
#define WMU_ONREADICON                  400
#define WMU_ONCACHESAVED                402
#define CSS_FILENAME                    420
#define CSS_NODELAY                     421
#define CSS_KEYPRESS                    422
#define CSS_DELAY                       423
#define CSS_DELAYTIME                   424
#define CSS_FULLPATHS                   425
#define CSS_LOOP                        426
#define CSS_NOTEPAD                     427
#define CSS_SELFDELETE                  428
#define CSS_SORTFILES                   429
#define CSS_FULLPATHS2                  429
#define FRN_SRC                         550
#define FRN_DST                         551
#define SAVEICO                         801
#define OPTIONSICO                      802
#define PRINTICO                        803
#define DELETEICO                       804
#define SLIDEICO                        805
#define HELPICO                         806
#define OPENICO                         807
#define EXITICO                         808
#define NEXTICO                         809
#define PREVICO                         810
#define NEWICO                          812
#define CLOSEALLICO                     813
#define ZOOMINICO                       814
#define ZOOMOUTICO                      815
#define ROTLEFTICO                      816
#define ROTRIGHTICO                     817
#define SIZE2WINICO                     818
#define SIZE2IMGICO                     819
#define FULLSCREENICO                   820
#define RELOADICO                       821
#define WINDOWEDICO                     822
#define CHECKMARKICO                    823
#define RESTOREICO                      824
#define INDEXICO                        825
#define CLRICO                          826
#define IINDEXICO                       827
#define CONTRASTMINICO                  828
#define CONTRASTMAXICO                  829
#define BRIGHTNESSMINICO                830
#define BRIGHTNESSMAXICO                831
#define SHARPNESSMINICO                 832
#define SHARPNESSMAXICO                 833
#define HUEMINICO                       834
#define HUEMAXICO                       835
#define SATURATIONMINICO                836
#define SATURATIONMAXICO                837
#define GAMMAMINICO                     838
#define GAMMAMAXICO                     839
#define LUMINANCEMINICO                 840
#define LUMINANCEMAXICO                 841
#define REDMINICO                       842
#define REDMAXICO                       843
#define GREENMINICO                     844
#define GREENMAXICO                     845
#define BLUEMINICO                      846
#define BLUEMAXICO                      847
#define FILEINFOICO                     848
#define LOGOICO                         853
#define SUO_DL_LANGUAGES                1005
#define SUO_C_TEXTURES                  1008
#define SUO_C_ASSOCIATE                 1009
#define SUO_T_LANGUAGES                 1010
#define SUO_T_TEXTURES                  1011
#define IDS_CONVERTING                  33300
#define IDS_CALCULATING                 33301
#define IDS_CALCHISTOGRAM               33302
#define IDS_OPTIMIZINGCLRS              33303
#define IDS_ADJUSTINGCOLORS             33304
#define IDS_DITHERING                   33305
#define IDS_RESAMPLING                  33306
#define IDS_OPENING                     33307
#define IDS_WRITING                     33308
#define IDS_DECOMPRESSING               33309
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        856
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1021
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
